---
title: "First Stage Aggregation"
author: "Mustafa Zia"
date: "5/24/2019"
output: html_document
---

```{r setup}
library(tidyverse)
library(readr)
library(readxl)
```


# Method 1 

Created a `function` that will download each individual file, unzips it and reads the file by creating an object. 
I HAVE TO ADD a PART To READ the RAW DATA as WELL!
```{r Reading_File, results = 'hide', eval=FALSE}
psd.function <- function(file)
    {

        my.file <- paste0("C:\\Users\\mustafa.zia\\Desktop\\FAS (PSD)\\",file,"_csv.zip") 
        url <- paste0("https://apps.fas.usda.gov/psdonline/downloads/",file,"_csv.zip") 
        download.file(url = url, destfile = my.file) # this downloads the zip file
        read_csv(unzip(my.file, exdir = "C:\\Users\\mustafa.zia\\Desktop\\FAS (PSD)"))

    }

psd.all.data                  <- psd.function(file = "psd_alldata")
psd.coffee                    <- psd.function(file = "psd_coffee")
psd.cotton                    <- psd.function(file = "psd_cotton")
psd.dairy                     <- psd.function(file = "psd_dairy")
psd.cotton                    <- psd.function(file = "psd_cotton")
psd.eu.area.prod              <- psd.function(file = "psd_eu_area_prod")
psd.fruits.veg                <- psd.function(file = "psd_fruits_vegetables")
psd.grains                    <- psd.function(file = "psd_grains_pulses")
psd.juice                     <- psd.function(file = "psd_juice")
psd.livstock.poultry          <- psd.function(file = "psd_livestock")
psd.oilseeds                  <- psd.function(file = "psd_oilseeds")
psd.russiabreakdown.area.prod <- psd.function(file = "psd_russiabreakdown_area_prod")
psd.sugar                     <- psd.function(file = "psd_sugar")
psd.tree.nuts                 <- psd.function(file = "psd_tree_nuts")

```

# Get the mapping file

```{r Get_Mapping_Files, results = 'hide' }
mapping.function <- function(file)
{
    read_excel(paste0("C:\\Users\\mustafa.zia\\Desktop\\FAS (PSD)\\Mapping\\",file,".xlsx"))
}                                      

attributes.data  <- mapping.function(file = "attributes")
commodities.data <- mapping.function(file = "commodities")
countries.data   <- mapping.function(file = "countries")
regions.data     <- mapping.function(file = "regions")
units.data       <- mapping.function(file = "units")
```


```{r}
Selected_Grains <- psd.grains %>% 
    filter(Commodity_Code %in% c("0459200", "0440000")) %>% 
    mutate(Commodity_Code = "Total Grains") %>% 
    group_by(Commodity_Code,Country_Name, Calendar_Year, Attribute_ID) %>%
    summarise(Amount = sum(Value)) %>% 
    bind_rows(psd.grains,.)

Check.Afghanistan_1 <- psd.grains %>% 
filter(Commodity_Code %in% c("0459200", "0440000"),Country_Name == "Afghanistan", Calendar_Year == 2006, Attribute_ID =="004") %>% 
summarise(Amount = sum(Value))
```



```{r}

# This reads all the sheets and turns each spececif sheet into a list 
ComCsvTs_Path  <- "C:\\Users\\mustafa.zia\\Desktop\\FAS (PSD)\\Mapping\\commodities.xlsx"
excel_sheets(path=ComCsvTs_Path)

tab_names <- excel_sheets(path=ComCsvTs_Path)
list_all <- lapply(tab_names,function(x) read_excel(path=ComCsvTs_Path, sheet = x))
```


```{r}
Read.Sheet <- function(sheet)
    
{
    read_excel(ComCsvTs_Path, sheet = sheet) # it would be a good idea to later turn the ComCsvTS into a list of different control/mapping files. That way you will have this particular function just reading the control files separately. Create another "macro" for the filepath. 
}

 commodities <- Read.Sheet("commodities")
 Poultry_Total <- Read.Sheet("Poultry_Chicken+Turkey")
 TOTGRNS    <- Read.Sheet("Total_Coarse_Grains")
 TOTSEED    <- Read.Sheet("Total_Oilseeds")

 # Here we will create the aggregates for the Total Grains
 Total.Grains <- psd.grains %>% 
    filter(Commodity_Code %in% TOTGRNS$Commodity_Code_New) %>% 
    mutate(Commodity_Code = "Total Grains") %>% 
    group_by(Commodity_Code,Commodity_Description, Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description) %>%
    summarise(Value = sum(Value)) %>% 
    bind_rows(psd.grains,.)
 
 Check.Afghanistan_2 <- Total.Grains %>% 
filter(Country_Name == "Afghanistan", Calendar_Year == 2006, Attribute_ID =="004") 
```

my.list = list("commodities","Poultry_Chicken+Turkey","Total_Coarse_Grains","Total_Oilseeds" )

